name: 'Omnidex Publish Docs'
description: 'Publish documentation from your repository to an Omnidex instance'

inputs:
  omnidex_url:
    description: 'Base URL of the Omnidex instance (e.g., https://docs.example.com)'
    required: true
  api_key:
    description: 'API key for authenticating with the Omnidex instance'
    required: true
  docs_path:
    description: 'Path to the documentation directory relative to the repository root'
    required: false
    default: 'docs'
  file_pattern:
    description: 'Glob pattern for documentation files'
    required: false
    default: '**/*.md'
  sync:
    description: 'Enable full sync mode to remove stale documents not present in this publish'
    required: false
    default: 'true'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/ksysoev/omnidex:latest'
  args:
    - publish
    - --url
    - ${{ inputs.omnidex_url }}
    - --docs-path
    - /github/workspace/${{ inputs.docs_path }}
    - --file-pattern
    - ${{ inputs.file_pattern }}
    - --sync=${{ inputs.sync }}
  env:
    OMNIDEX_API_KEY: ${{ inputs.api_key }}
