// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package api

import (
	io "io"

	core "github.com/ksysoev/omnidex/pkg/core"

	mock "github.com/stretchr/testify/mock"
)

// MockViewRenderer is an autogenerated mock type for the ViewRenderer type
type MockViewRenderer struct {
	mock.Mock
}

type MockViewRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockViewRenderer) EXPECT() *MockViewRenderer_Expecter {
	return &MockViewRenderer_Expecter{mock: &_m.Mock}
}

// RenderDoc provides a mock function with given fields: w, doc, html, navDocs, partial
func (_m *MockViewRenderer) RenderDoc(w io.Writer, doc core.Document, html []byte, navDocs []core.DocumentMeta, partial bool) error {
	ret := _m.Called(w, doc, html, navDocs, partial)

	if len(ret) == 0 {
		panic("no return value specified for RenderDoc")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Writer, core.Document, []byte, []core.DocumentMeta, bool) error); ok {
		r0 = rf(w, doc, html, navDocs, partial)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViewRenderer_RenderDoc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderDoc'
type MockViewRenderer_RenderDoc_Call struct {
	*mock.Call
}

// RenderDoc is a helper method to define mock.On call
//   - w io.Writer
//   - doc core.Document
//   - html []byte
//   - navDocs []core.DocumentMeta
//   - partial bool
func (_e *MockViewRenderer_Expecter) RenderDoc(w interface{}, doc interface{}, html interface{}, navDocs interface{}, partial interface{}) *MockViewRenderer_RenderDoc_Call {
	return &MockViewRenderer_RenderDoc_Call{Call: _e.mock.On("RenderDoc", w, doc, html, navDocs, partial)}
}

func (_c *MockViewRenderer_RenderDoc_Call) Run(run func(w io.Writer, doc core.Document, html []byte, navDocs []core.DocumentMeta, partial bool)) *MockViewRenderer_RenderDoc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Writer), args[1].(core.Document), args[2].([]byte), args[3].([]core.DocumentMeta), args[4].(bool))
	})
	return _c
}

func (_c *MockViewRenderer_RenderDoc_Call) Return(_a0 error) *MockViewRenderer_RenderDoc_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViewRenderer_RenderDoc_Call) RunAndReturn(run func(io.Writer, core.Document, []byte, []core.DocumentMeta, bool) error) *MockViewRenderer_RenderDoc_Call {
	_c.Call.Return(run)
	return _c
}

// RenderHome provides a mock function with given fields: w, repos, partial
func (_m *MockViewRenderer) RenderHome(w io.Writer, repos []core.RepoInfo, partial bool) error {
	ret := _m.Called(w, repos, partial)

	if len(ret) == 0 {
		panic("no return value specified for RenderHome")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Writer, []core.RepoInfo, bool) error); ok {
		r0 = rf(w, repos, partial)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViewRenderer_RenderHome_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderHome'
type MockViewRenderer_RenderHome_Call struct {
	*mock.Call
}

// RenderHome is a helper method to define mock.On call
//   - w io.Writer
//   - repos []core.RepoInfo
//   - partial bool
func (_e *MockViewRenderer_Expecter) RenderHome(w interface{}, repos interface{}, partial interface{}) *MockViewRenderer_RenderHome_Call {
	return &MockViewRenderer_RenderHome_Call{Call: _e.mock.On("RenderHome", w, repos, partial)}
}

func (_c *MockViewRenderer_RenderHome_Call) Run(run func(w io.Writer, repos []core.RepoInfo, partial bool)) *MockViewRenderer_RenderHome_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Writer), args[1].([]core.RepoInfo), args[2].(bool))
	})
	return _c
}

func (_c *MockViewRenderer_RenderHome_Call) Return(_a0 error) *MockViewRenderer_RenderHome_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViewRenderer_RenderHome_Call) RunAndReturn(run func(io.Writer, []core.RepoInfo, bool) error) *MockViewRenderer_RenderHome_Call {
	_c.Call.Return(run)
	return _c
}

// RenderNotFound provides a mock function with given fields: w
func (_m *MockViewRenderer) RenderNotFound(w io.Writer) error {
	ret := _m.Called(w)

	if len(ret) == 0 {
		panic("no return value specified for RenderNotFound")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Writer) error); ok {
		r0 = rf(w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViewRenderer_RenderNotFound_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderNotFound'
type MockViewRenderer_RenderNotFound_Call struct {
	*mock.Call
}

// RenderNotFound is a helper method to define mock.On call
//   - w io.Writer
func (_e *MockViewRenderer_Expecter) RenderNotFound(w interface{}) *MockViewRenderer_RenderNotFound_Call {
	return &MockViewRenderer_RenderNotFound_Call{Call: _e.mock.On("RenderNotFound", w)}
}

func (_c *MockViewRenderer_RenderNotFound_Call) Run(run func(w io.Writer)) *MockViewRenderer_RenderNotFound_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Writer))
	})
	return _c
}

func (_c *MockViewRenderer_RenderNotFound_Call) Return(_a0 error) *MockViewRenderer_RenderNotFound_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViewRenderer_RenderNotFound_Call) RunAndReturn(run func(io.Writer) error) *MockViewRenderer_RenderNotFound_Call {
	_c.Call.Return(run)
	return _c
}

// RenderRepoIndex provides a mock function with given fields: w, repo, docs, partial
func (_m *MockViewRenderer) RenderRepoIndex(w io.Writer, repo string, docs []core.DocumentMeta, partial bool) error {
	ret := _m.Called(w, repo, docs, partial)

	if len(ret) == 0 {
		panic("no return value specified for RenderRepoIndex")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Writer, string, []core.DocumentMeta, bool) error); ok {
		r0 = rf(w, repo, docs, partial)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViewRenderer_RenderRepoIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderRepoIndex'
type MockViewRenderer_RenderRepoIndex_Call struct {
	*mock.Call
}

// RenderRepoIndex is a helper method to define mock.On call
//   - w io.Writer
//   - repo string
//   - docs []core.DocumentMeta
//   - partial bool
func (_e *MockViewRenderer_Expecter) RenderRepoIndex(w interface{}, repo interface{}, docs interface{}, partial interface{}) *MockViewRenderer_RenderRepoIndex_Call {
	return &MockViewRenderer_RenderRepoIndex_Call{Call: _e.mock.On("RenderRepoIndex", w, repo, docs, partial)}
}

func (_c *MockViewRenderer_RenderRepoIndex_Call) Run(run func(w io.Writer, repo string, docs []core.DocumentMeta, partial bool)) *MockViewRenderer_RenderRepoIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Writer), args[1].(string), args[2].([]core.DocumentMeta), args[3].(bool))
	})
	return _c
}

func (_c *MockViewRenderer_RenderRepoIndex_Call) Return(_a0 error) *MockViewRenderer_RenderRepoIndex_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViewRenderer_RenderRepoIndex_Call) RunAndReturn(run func(io.Writer, string, []core.DocumentMeta, bool) error) *MockViewRenderer_RenderRepoIndex_Call {
	_c.Call.Return(run)
	return _c
}

// RenderSearch provides a mock function with given fields: w, query, results, partial
func (_m *MockViewRenderer) RenderSearch(w io.Writer, query string, results *core.SearchResults, partial bool) error {
	ret := _m.Called(w, query, results, partial)

	if len(ret) == 0 {
		panic("no return value specified for RenderSearch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Writer, string, *core.SearchResults, bool) error); ok {
		r0 = rf(w, query, results, partial)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockViewRenderer_RenderSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderSearch'
type MockViewRenderer_RenderSearch_Call struct {
	*mock.Call
}

// RenderSearch is a helper method to define mock.On call
//   - w io.Writer
//   - query string
//   - results *core.SearchResults
//   - partial bool
func (_e *MockViewRenderer_Expecter) RenderSearch(w interface{}, query interface{}, results interface{}, partial interface{}) *MockViewRenderer_RenderSearch_Call {
	return &MockViewRenderer_RenderSearch_Call{Call: _e.mock.On("RenderSearch", w, query, results, partial)}
}

func (_c *MockViewRenderer_RenderSearch_Call) Run(run func(w io.Writer, query string, results *core.SearchResults, partial bool)) *MockViewRenderer_RenderSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Writer), args[1].(string), args[2].(*core.SearchResults), args[3].(bool))
	})
	return _c
}

func (_c *MockViewRenderer_RenderSearch_Call) Return(_a0 error) *MockViewRenderer_RenderSearch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockViewRenderer_RenderSearch_Call) RunAndReturn(run func(io.Writer, string, *core.SearchResults, bool) error) *MockViewRenderer_RenderSearch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockViewRenderer creates a new instance of MockViewRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockViewRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockViewRenderer {
	mock := &MockViewRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
