openapi: "3.0.3"
info:
  title: Petstore API
  description: |
    A sample API that uses a petstore as an example to demonstrate features
    in the OpenAPI 3.0 specification. This is a simplified version of the
    classic Petstore example, designed to showcase how Omnidex renders
    OpenAPI specs via Swagger UI.
  version: "1.0.0"
  contact:
    name: Petstore API Support
    url: https://example.com/support
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://petstore.example.com/v1
    description: Production server

tags:
  - name: pets
    description: Everything about your Pets
  - name: store
    description: Access to Petstore orders

paths:
  /pets:
    get:
      tags:
        - pets
      summary: List all pets
      description: Returns all pets from the system that the user has access to.
      operationId: listPets
      parameters:
        - name: limit
          in: query
          description: Maximum number of pets to return
          required: false
          schema:
            type: integer
            format: int32
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Number of pets to skip for pagination
          required: false
          schema:
            type: integer
            format: int32
            default: 0
      responses:
        "200":
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"
        "500":
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      tags:
        - pets
      summary: Create a pet
      description: Creates a new pet in the store.
      operationId: createPet
      requestBody:
        description: Pet to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewPet"
      responses:
        "201":
          description: Pet created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /pets/{petId}:
    get:
      tags:
        - pets
      summary: Get a pet by ID
      description: Returns a single pet by its identifier.
      operationId: showPetById
      parameters:
        - name: petId
          in: path
          required: true
          description: The ID of the pet to retrieve
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        "404":
          description: Pet not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - pets
      summary: Delete a pet
      description: Deletes a single pet by its identifier.
      operationId: deletePet
      parameters:
        - name: petId
          in: path
          required: true
          description: The ID of the pet to delete
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: Pet deleted successfully
        "404":
          description: Pet not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /store/inventory:
    get:
      tags:
        - store
      summary: Returns pet inventories by status
      description: Returns a map of status codes to quantities.
      operationId: getInventory
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                  format: int32

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the pet
        name:
          type: string
          description: Name of the pet
        tag:
          type: string
          description: Optional tag/category for the pet
        status:
          type: string
          description: Pet status in the store
          enum:
            - available
            - pending
            - sold

    NewPet:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the pet
        tag:
          type: string
          description: Optional tag/category for the pet

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Human-readable error message
