// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package core

import mock "github.com/stretchr/testify/mock"

// MockContentProcessor is an autogenerated mock type for the ContentProcessor type
type MockContentProcessor struct {
	mock.Mock
}

type MockContentProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContentProcessor) EXPECT() *MockContentProcessor_Expecter {
	return &MockContentProcessor_Expecter{mock: &_m.Mock}
}

// ExtractTitle provides a mock function with given fields: src
func (_m *MockContentProcessor) ExtractTitle(src []byte) string {
	ret := _m.Called(src)

	if len(ret) == 0 {
		panic("no return value specified for ExtractTitle")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = rf(src)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockContentProcessor_ExtractTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractTitle'
type MockContentProcessor_ExtractTitle_Call struct {
	*mock.Call
}

// ExtractTitle is a helper method to define mock.On call
//   - src []byte
func (_e *MockContentProcessor_Expecter) ExtractTitle(src interface{}) *MockContentProcessor_ExtractTitle_Call {
	return &MockContentProcessor_ExtractTitle_Call{Call: _e.mock.On("ExtractTitle", src)}
}

func (_c *MockContentProcessor_ExtractTitle_Call) Run(run func(src []byte)) *MockContentProcessor_ExtractTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockContentProcessor_ExtractTitle_Call) Return(_a0 string) *MockContentProcessor_ExtractTitle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContentProcessor_ExtractTitle_Call) RunAndReturn(run func([]byte) string) *MockContentProcessor_ExtractTitle_Call {
	_c.Call.Return(run)
	return _c
}

// RenderHTML provides a mock function with given fields: src
func (_m *MockContentProcessor) RenderHTML(src []byte) ([]byte, []Heading, error) {
	ret := _m.Called(src)

	if len(ret) == 0 {
		panic("no return value specified for RenderHTML")
	}

	var r0 []byte
	var r1 []Heading
	var r2 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, []Heading, error)); ok {
		return rf(src)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(src)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) []Heading); ok {
		r1 = rf(src)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]Heading)
		}
	}

	if rf, ok := ret.Get(2).(func([]byte) error); ok {
		r2 = rf(src)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockContentProcessor_RenderHTML_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderHTML'
type MockContentProcessor_RenderHTML_Call struct {
	*mock.Call
}

// RenderHTML is a helper method to define mock.On call
//   - src []byte
func (_e *MockContentProcessor_Expecter) RenderHTML(src interface{}) *MockContentProcessor_RenderHTML_Call {
	return &MockContentProcessor_RenderHTML_Call{Call: _e.mock.On("RenderHTML", src)}
}

func (_c *MockContentProcessor_RenderHTML_Call) Run(run func(src []byte)) *MockContentProcessor_RenderHTML_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockContentProcessor_RenderHTML_Call) Return(_a0 []byte, _a1 []Heading, _a2 error) *MockContentProcessor_RenderHTML_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockContentProcessor_RenderHTML_Call) RunAndReturn(run func([]byte) ([]byte, []Heading, error)) *MockContentProcessor_RenderHTML_Call {
	_c.Call.Return(run)
	return _c
}

// ToPlainText provides a mock function with given fields: src
func (_m *MockContentProcessor) ToPlainText(src []byte) string {
	ret := _m.Called(src)

	if len(ret) == 0 {
		panic("no return value specified for ToPlainText")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = rf(src)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockContentProcessor_ToPlainText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToPlainText'
type MockContentProcessor_ToPlainText_Call struct {
	*mock.Call
}

// ToPlainText is a helper method to define mock.On call
//   - src []byte
func (_e *MockContentProcessor_Expecter) ToPlainText(src interface{}) *MockContentProcessor_ToPlainText_Call {
	return &MockContentProcessor_ToPlainText_Call{Call: _e.mock.On("ToPlainText", src)}
}

func (_c *MockContentProcessor_ToPlainText_Call) Run(run func(src []byte)) *MockContentProcessor_ToPlainText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockContentProcessor_ToPlainText_Call) Return(_a0 string) *MockContentProcessor_ToPlainText_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContentProcessor_ToPlainText_Call) RunAndReturn(run func([]byte) string) *MockContentProcessor_ToPlainText_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockContentProcessor creates a new instance of MockContentProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContentProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContentProcessor {
	mock := &MockContentProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
