// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package core

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockdocStore is an autogenerated mock type for the docStore type
type MockdocStore struct {
	mock.Mock
}

type MockdocStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockdocStore) EXPECT() *MockdocStore_Expecter {
	return &MockdocStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, repo, path
func (_m *MockdocStore) Delete(ctx context.Context, repo string, path string) error {
	ret := _m.Called(ctx, repo, path)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, repo, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockdocStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockdocStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - path string
func (_e *MockdocStore_Expecter) Delete(ctx interface{}, repo interface{}, path interface{}) *MockdocStore_Delete_Call {
	return &MockdocStore_Delete_Call{Call: _e.mock.On("Delete", ctx, repo, path)}
}

func (_c *MockdocStore_Delete_Call) Run(run func(ctx context.Context, repo string, path string)) *MockdocStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockdocStore_Delete_Call) Return(_a0 error) *MockdocStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockdocStore_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockdocStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, repo, path
func (_m *MockdocStore) Get(ctx context.Context, repo string, path string) (Document, error) {
	ret := _m.Called(ctx, repo, path)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (Document, error)); ok {
		return rf(ctx, repo, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) Document); ok {
		r0 = rf(ctx, repo, path)
	} else {
		r0 = ret.Get(0).(Document)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, repo, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockdocStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockdocStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - path string
func (_e *MockdocStore_Expecter) Get(ctx interface{}, repo interface{}, path interface{}) *MockdocStore_Get_Call {
	return &MockdocStore_Get_Call{Call: _e.mock.On("Get", ctx, repo, path)}
}

func (_c *MockdocStore_Get_Call) Run(run func(ctx context.Context, repo string, path string)) *MockdocStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockdocStore_Get_Call) Return(_a0 Document, _a1 error) *MockdocStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockdocStore_Get_Call) RunAndReturn(run func(context.Context, string, string) (Document, error)) *MockdocStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, repo
func (_m *MockdocStore) List(ctx context.Context, repo string) ([]DocumentMeta, error) {
	ret := _m.Called(ctx, repo)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []DocumentMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]DocumentMeta, error)); ok {
		return rf(ctx, repo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []DocumentMeta); ok {
		r0 = rf(ctx, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DocumentMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, repo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockdocStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockdocStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
func (_e *MockdocStore_Expecter) List(ctx interface{}, repo interface{}) *MockdocStore_List_Call {
	return &MockdocStore_List_Call{Call: _e.mock.On("List", ctx, repo)}
}

func (_c *MockdocStore_List_Call) Run(run func(ctx context.Context, repo string)) *MockdocStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockdocStore_List_Call) Return(_a0 []DocumentMeta, _a1 error) *MockdocStore_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockdocStore_List_Call) RunAndReturn(run func(context.Context, string) ([]DocumentMeta, error)) *MockdocStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListRepos provides a mock function with given fields: ctx
func (_m *MockdocStore) ListRepos(ctx context.Context) ([]RepoInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRepos")
	}

	var r0 []RepoInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]RepoInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []RepoInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]RepoInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockdocStore_ListRepos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRepos'
type MockdocStore_ListRepos_Call struct {
	*mock.Call
}

// ListRepos is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockdocStore_Expecter) ListRepos(ctx interface{}) *MockdocStore_ListRepos_Call {
	return &MockdocStore_ListRepos_Call{Call: _e.mock.On("ListRepos", ctx)}
}

func (_c *MockdocStore_ListRepos_Call) Run(run func(ctx context.Context)) *MockdocStore_ListRepos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockdocStore_ListRepos_Call) Return(_a0 []RepoInfo, _a1 error) *MockdocStore_ListRepos_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockdocStore_ListRepos_Call) RunAndReturn(run func(context.Context) ([]RepoInfo, error)) *MockdocStore_ListRepos_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, doc
func (_m *MockdocStore) Save(ctx context.Context, doc Document) error {
	ret := _m.Called(ctx, doc)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, Document) error); ok {
		r0 = rf(ctx, doc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockdocStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockdocStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - doc Document
func (_e *MockdocStore_Expecter) Save(ctx interface{}, doc interface{}) *MockdocStore_Save_Call {
	return &MockdocStore_Save_Call{Call: _e.mock.On("Save", ctx, doc)}
}

func (_c *MockdocStore_Save_Call) Run(run func(ctx context.Context, doc Document)) *MockdocStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(Document))
	})
	return _c
}

func (_c *MockdocStore_Save_Call) Return(_a0 error) *MockdocStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockdocStore_Save_Call) RunAndReturn(run func(context.Context, Document) error) *MockdocStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockdocStore creates a new instance of MockdocStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdocStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockdocStore {
	mock := &MockdocStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
