// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package core

import mock "github.com/stretchr/testify/mock"

// MockmarkdownRenderer is an autogenerated mock type for the markdownRenderer type
type MockmarkdownRenderer struct {
	mock.Mock
}

type MockmarkdownRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockmarkdownRenderer) EXPECT() *MockmarkdownRenderer_Expecter {
	return &MockmarkdownRenderer_Expecter{mock: &_m.Mock}
}

// ExtractHeadings provides a mock function with given fields: src
func (_m *MockmarkdownRenderer) ExtractHeadings(src []byte) []Heading {
	ret := _m.Called(src)

	if len(ret) == 0 {
		panic("no return value specified for ExtractHeadings")
	}

	var r0 []Heading
	if rf, ok := ret.Get(0).(func([]byte) []Heading); ok {
		r0 = rf(src)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Heading)
		}
	}

	return r0
}

// MockmarkdownRenderer_ExtractHeadings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractHeadings'
type MockmarkdownRenderer_ExtractHeadings_Call struct {
	*mock.Call
}

// ExtractHeadings is a helper method to define mock.On call
//   - src []byte
func (_e *MockmarkdownRenderer_Expecter) ExtractHeadings(src interface{}) *MockmarkdownRenderer_ExtractHeadings_Call {
	return &MockmarkdownRenderer_ExtractHeadings_Call{Call: _e.mock.On("ExtractHeadings", src)}
}

func (_c *MockmarkdownRenderer_ExtractHeadings_Call) Run(run func(src []byte)) *MockmarkdownRenderer_ExtractHeadings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockmarkdownRenderer_ExtractHeadings_Call) Return(_a0 []Heading) *MockmarkdownRenderer_ExtractHeadings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockmarkdownRenderer_ExtractHeadings_Call) RunAndReturn(run func([]byte) []Heading) *MockmarkdownRenderer_ExtractHeadings_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractTitle provides a mock function with given fields: src
func (_m *MockmarkdownRenderer) ExtractTitle(src []byte) string {
	ret := _m.Called(src)

	if len(ret) == 0 {
		panic("no return value specified for ExtractTitle")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = rf(src)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockmarkdownRenderer_ExtractTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractTitle'
type MockmarkdownRenderer_ExtractTitle_Call struct {
	*mock.Call
}

// ExtractTitle is a helper method to define mock.On call
//   - src []byte
func (_e *MockmarkdownRenderer_Expecter) ExtractTitle(src interface{}) *MockmarkdownRenderer_ExtractTitle_Call {
	return &MockmarkdownRenderer_ExtractTitle_Call{Call: _e.mock.On("ExtractTitle", src)}
}

func (_c *MockmarkdownRenderer_ExtractTitle_Call) Run(run func(src []byte)) *MockmarkdownRenderer_ExtractTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockmarkdownRenderer_ExtractTitle_Call) Return(_a0 string) *MockmarkdownRenderer_ExtractTitle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockmarkdownRenderer_ExtractTitle_Call) RunAndReturn(run func([]byte) string) *MockmarkdownRenderer_ExtractTitle_Call {
	_c.Call.Return(run)
	return _c
}

// ToHTML provides a mock function with given fields: src
func (_m *MockmarkdownRenderer) ToHTML(src []byte) ([]byte, error) {
	ret := _m.Called(src)

	if len(ret) == 0 {
		panic("no return value specified for ToHTML")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return rf(src)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(src)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(src)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockmarkdownRenderer_ToHTML_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToHTML'
type MockmarkdownRenderer_ToHTML_Call struct {
	*mock.Call
}

// ToHTML is a helper method to define mock.On call
//   - src []byte
func (_e *MockmarkdownRenderer_Expecter) ToHTML(src interface{}) *MockmarkdownRenderer_ToHTML_Call {
	return &MockmarkdownRenderer_ToHTML_Call{Call: _e.mock.On("ToHTML", src)}
}

func (_c *MockmarkdownRenderer_ToHTML_Call) Run(run func(src []byte)) *MockmarkdownRenderer_ToHTML_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockmarkdownRenderer_ToHTML_Call) Return(_a0 []byte, _a1 error) *MockmarkdownRenderer_ToHTML_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockmarkdownRenderer_ToHTML_Call) RunAndReturn(run func([]byte) ([]byte, error)) *MockmarkdownRenderer_ToHTML_Call {
	_c.Call.Return(run)
	return _c
}

// ToPlainText provides a mock function with given fields: src
func (_m *MockmarkdownRenderer) ToPlainText(src []byte) string {
	ret := _m.Called(src)

	if len(ret) == 0 {
		panic("no return value specified for ToPlainText")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = rf(src)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockmarkdownRenderer_ToPlainText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToPlainText'
type MockmarkdownRenderer_ToPlainText_Call struct {
	*mock.Call
}

// ToPlainText is a helper method to define mock.On call
//   - src []byte
func (_e *MockmarkdownRenderer_Expecter) ToPlainText(src interface{}) *MockmarkdownRenderer_ToPlainText_Call {
	return &MockmarkdownRenderer_ToPlainText_Call{Call: _e.mock.On("ToPlainText", src)}
}

func (_c *MockmarkdownRenderer_ToPlainText_Call) Run(run func(src []byte)) *MockmarkdownRenderer_ToPlainText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockmarkdownRenderer_ToPlainText_Call) Return(_a0 string) *MockmarkdownRenderer_ToPlainText_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockmarkdownRenderer_ToPlainText_Call) RunAndReturn(run func([]byte) string) *MockmarkdownRenderer_ToPlainText_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockmarkdownRenderer creates a new instance of MockmarkdownRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockmarkdownRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockmarkdownRenderer {
	mock := &MockmarkdownRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
