// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package core

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MocksearchEngine is an autogenerated mock type for the searchEngine type
type MocksearchEngine struct {
	mock.Mock
}

type MocksearchEngine_Expecter struct {
	mock *mock.Mock
}

func (_m *MocksearchEngine) EXPECT() *MocksearchEngine_Expecter {
	return &MocksearchEngine_Expecter{mock: &_m.Mock}
}

// Index provides a mock function with given fields: ctx, doc, plainText
func (_m *MocksearchEngine) Index(ctx context.Context, doc Document, plainText string) error {
	ret := _m.Called(ctx, doc, plainText)

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, Document, string) error); ok {
		r0 = rf(ctx, doc, plainText)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MocksearchEngine_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type MocksearchEngine_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
//   - ctx context.Context
//   - doc Document
//   - plainText string
func (_e *MocksearchEngine_Expecter) Index(ctx interface{}, doc interface{}, plainText interface{}) *MocksearchEngine_Index_Call {
	return &MocksearchEngine_Index_Call{Call: _e.mock.On("Index", ctx, doc, plainText)}
}

func (_c *MocksearchEngine_Index_Call) Run(run func(ctx context.Context, doc Document, plainText string)) *MocksearchEngine_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(Document), args[2].(string))
	})
	return _c
}

func (_c *MocksearchEngine_Index_Call) Return(_a0 error) *MocksearchEngine_Index_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MocksearchEngine_Index_Call) RunAndReturn(run func(context.Context, Document, string) error) *MocksearchEngine_Index_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, docID
func (_m *MocksearchEngine) Remove(ctx context.Context, docID string) error {
	ret := _m.Called(ctx, docID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, docID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MocksearchEngine_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MocksearchEngine_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - docID string
func (_e *MocksearchEngine_Expecter) Remove(ctx interface{}, docID interface{}) *MocksearchEngine_Remove_Call {
	return &MocksearchEngine_Remove_Call{Call: _e.mock.On("Remove", ctx, docID)}
}

func (_c *MocksearchEngine_Remove_Call) Run(run func(ctx context.Context, docID string)) *MocksearchEngine_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MocksearchEngine_Remove_Call) Return(_a0 error) *MocksearchEngine_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MocksearchEngine_Remove_Call) RunAndReturn(run func(context.Context, string) error) *MocksearchEngine_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, query, opts
func (_m *MocksearchEngine) Search(ctx context.Context, query string, opts SearchOpts) (*SearchResults, error) {
	ret := _m.Called(ctx, query, opts)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *SearchResults
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, SearchOpts) (*SearchResults, error)); ok {
		return rf(ctx, query, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, SearchOpts) *SearchResults); ok {
		r0 = rf(ctx, query, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SearchResults)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, SearchOpts) error); ok {
		r1 = rf(ctx, query, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MocksearchEngine_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MocksearchEngine_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - opts SearchOpts
func (_e *MocksearchEngine_Expecter) Search(ctx interface{}, query interface{}, opts interface{}) *MocksearchEngine_Search_Call {
	return &MocksearchEngine_Search_Call{Call: _e.mock.On("Search", ctx, query, opts)}
}

func (_c *MocksearchEngine_Search_Call) Run(run func(ctx context.Context, query string, opts SearchOpts)) *MocksearchEngine_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(SearchOpts))
	})
	return _c
}

func (_c *MocksearchEngine_Search_Call) Return(_a0 *SearchResults, _a1 error) *MocksearchEngine_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MocksearchEngine_Search_Call) RunAndReturn(run func(context.Context, string, SearchOpts) (*SearchResults, error)) *MocksearchEngine_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocksearchEngine creates a new instance of MocksearchEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocksearchEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocksearchEngine {
	mock := &MocksearchEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
